### ISSUE TITLE
ios浏览器合集

### ISSUE THREAD

**Issue by zoujinglong666** [fantastic-mobile/basic#1]
ios使用你们的演示基础版地址 
滚动容易触发两个滚动条 体验不好
跳转页面时每次都是滑动到页面下一点  而不是直接顶部
页面缓存失效

**Comment by hooray** [comment]
我在iphone 15模拟器下测试没有你是说的问题，需要你提供下更详细的复现场景要求和步骤。

另外一个issue里只反馈一个问题，页面缓存没发现有问题，如果有问题请新开issue
